project:
  type: website
  output-dir: docs

website:
  title: "iNat Earthworm Taxonomy"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show code"

