---
title: "species-comparison"
author: "Cenaida Largo"
format: html
editor: visual
---

## Overview

This script explores the alignment of the iNaturalist earthworm (Crassiclitellata) taxonomy with:

- **WoRMS** (World Register of Marine Species), the current taxonomy source used by iNaturalist.

- **Misırlıoğlu et al. (2023)**, an updated global checklist of valid earthworm species.

Subspecies are excluded from this analysis.

## Setup

Package versions are tracked with \`renv\`.

```{r}
#| message: false
#| warning: false

library(here)    #Project relative file paths
library(readr)   #Import data files into R
library(readxl)  #Import excel files into R
library(dplyr)   #Manipulating data
library(stringr) #Manipulating text
```

## Data sources

### iNaturalist

Download all “active” names from the **iNaturalist Taxonomy DarwinCore Archive** at

<https://www.inaturalist.org/pages/developers>

Updated monthly.

### WoRMS

**WoRMS taxon list** downloads are available at

<https://www.marinespecies.org/aphia.php?p=download&what=taxlist>

Because the web interface limits exports to 1000 rows, a custom export was requested using:

<https://www.marinespecies.org/usersrequest.php>

Requested fields:

- ScientificName

- Authority

- taxonRank

- taxonomicStatus

- Classification

- Accepted taxon information.

Make sure to change the environment field from “marine = yes” to “marine = any”.

Contact: info(at)marinespecies.org

### **Misirlioğlu 2023**

**Reference to this dataset:** Brown, G.G., James, S.W., Csuzdi, C., Lapied, E., Decaëns, T., Reynolds, J.W., Mısırlıoğlu, M., Stovanić, M., Trakić, T., Sekulić, J., Phillips, H., Cameron, E. (2023) A checklist of megadrile earthworm (Annelida: Clitellata) species and subspecies of the world. Zenodo, <https://doi.org/10.5281/zenodo.7301848>

**Reference to original manuscript:** Mısırlıoğlu, M., Reynolds, J.W., Stovanić, M, Trakić, T, Sekulić, J., James, S.W., Csuzdi, C., Decaëns, T., Lapied, E., Phillips, H.R.P., Cameron, E.K, Brown, G.G. (2023) Earthworms (Clitellata, Megadrili) of the world: an updated checklist of valid species and families, with notes on their distribution. Zootaxa.
